#!/bin/sh

if test -d cexp ; then
	(cd cexp; make src)
fi

# for some strange reason it is not
# possible to pass autoreconf an option
# directing it to serach directories
# for '.m4' files for aclocal. The '-I/-B'
# options don't seem to work. We hack
# around this by setting ACLOCAL
if test "${ACLOCAL+set}" = "set" ; then
	echo "Warning: ACLOCAL is already set; I add a -I option";
else
	ACLOCAL=aclocal
fi
export	ACLOCAL="$ACLOCAL -I `(cd \`dirname $0\`; pwd)`/autognu"
autoreconf -i
