#!/bin/sh

localhack=
while getopts "lf" theopt ; do
	case $theopt in
		l)
			localhack=yes
		;;
		f)
			force=--force
		;;
		*)
		;;
	esac
done

if test -d cexp ; then
	(cd cexp; make src)
fi

for val in cexp/binutils* binutils* ; do
	if test -d "$val" ; then
		echo "***************  ERROR Found $val;"
		echo "You must run `basename $0` before unpacking 'binutils';"
		echo "Please move the 'binutils' directory temporarily out of the source tree,"
		echo "run `basename $0` and then move binutils back"
		exit 1
	fi
done

if test "$localhack" = "yes" ; then
# for some strange reason it is not
# possible to pass autoreconf an option
# directing it to search directories
# for '.m4' files for aclocal. The '-I/-B'
# options don't seem to work. We hack
# around this by setting ACLOCAL
	if test "${ACLOCAL+set}" = "set" ; then
		echo "Warning: ACLOCAL is already set; I add a -I option";
	else
		ACLOCAL=aclocal
	fi
	export	ACLOCAL="$ACLOCAL -I `(cd \`dirname $0\`; pwd)`/autognu"
fi
autoreconf -i $force

if test -d system/ldep ; then
	(cd system/ldep; ./bootstrap)
fi
